defaults:
- _self_
- data: data
- learning: learning
- hydra: hydra

inference: False
inference_path: /home/nibdombe/deep_eit/outputs/2024-07-04/10-29-27
segmentation_model: False
wandb: 'online' # 'disabled', 'online', 'offline'

