defaults:
- _self_
- data: data 
- learning: learning 
- hydra: hydra

model_type: resist  # resist, resist_single, linear, ...
seed: 89 #12 23 34 45 56
inference: False
inference_path: outputs/2024-07-04/10-29-27
wandb: 'online' # 'disabled', 'online', 'offline'

