defaults:
- _self_
- data: data #data, data_linear
- learning: learning #learning, learning_linear
- hydra: hydra

model_type: resist_single  # resist, resist_single, linear, ...
inference: False
inference_path: outputs/2024-07-04/10-29-27
wandb: 'online' # 'disabled', 'online', 'offline'

