model:
  _target_: model.models.AttentionModelCNN
  # conv_out_channels: 32 
  # conv_in_channels: 1 
  # conv_blocks: 5 
  # conv_features: 64 
  nodes_resistance_network: 256
  resistance_network_blocks: 2 # not used
  nodes_signal_network: 256  # not used
  signal_network_blocks: 4 # not used
  signals_dim: 128
  num_encoding_functions: 10
  num_attention_blocks: 4
  num_electrodes: 16
  num_position_embedding: 4
  num_level_embdedding: 4
  num_linear_output_blocks: 3
  use_cnn: False
  cnn_in_channels: 16
  cnn_out_channels: 32
  prob_dropout: 0.7

segmentation_model:
  _target_: segmentation.models.SegmentationModel
  in_channels: 1
  out_channels: 32  
  blocks: 3
  learning_rate: 0.0001
  batch_size: 16

training:
  epochs: 80
  batch_size_train: 3
  batch_size_val: 1
  learning_rate: 0.00001
  sample_points: 1000
  device: cuda

testing:
  batch_size_test: 2

